#ifndef INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHVARIABLEHEADER_H
#define INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHVARIABLEHEADER_H

namespace cleanMqtt
{
	namespace mqtt
	{
		namespace packets
		{
			struct PublishVariableHeader
			{
			};
		}
	}
}

#endif //INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHVARIABLEHEADER_H 