#ifndef INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHPAYLOADHEADER_H
#define INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHPAYLOADHEADER_H

namespace cleanMqtt
{
	namespace mqtt
	{
		namespace packets
		{
			struct PublishPayloadHeader
			{

			};
		}
	}
}

#endif //INTERFACE_CLEANMQTT_MQTT_PACKETS_PUBLISH_HEADERS_PUBLISHPAYLOADHEADER_H 